### ISSUE TITLE
Update the cloud-gov training tracker spreadsheet

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#1286]
https://drive.google.com/open?id=17LPbVR-ibZ7W5tURNGKmtHSP-5OI0npU3LImcUYOYtA PeterB / compliance needs to own this and ensure it's update to date and accurate. 

From the onboarding:

- [ ] Add their name, whether they're Cloud Ops (Platform), and the date they joined the team to the training tracker. Copy the formulas for the due dates from an existing row (grab the "corner" of the cells and pull down).
- [ ] As they complete training, fill out their completion dates in the training tracker.

Acceptance Criteria:

- [ ] All cloud-gov users have accurate dates in the tracker
- [ ] The associated trainings have links back to the tracker

It may also be worthwhile to make the onboarding process easier to track and update as an associated epic.

**Comment by pburkholder** [comment]
Looks like I did this as gravel work leading up to spring trainings
