### ISSUE TITLE
Ensure MFA enforcement for use of AWS access keys 

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#1364]
# What we're after

In addition to MFA for AWS console, enforce (and monitor) use of MFA for access keys.  This is a task under #1262:

I propose we add `self-managed-credentials` policy, https://github.com/cloud-gov/cg-provision/blob/master/terraform/modules/iam_role_policy/self_managed_credentials/policy.json, to our Administrators group. This would close out this issue's point #3, "Stop using long-lived, unencrypted AWS credentials", which I originally thought would have to be done client side.

The policy includes:

```
     {
          "Sid": "DenyAllExceptListedIfNoMFA",
          "Effect": "Deny",
          "NotAction": [
              "iam:CreateVirtualMFADevice",
              "iam:EnableMFADevice",
              "iam:GetUser",
              "iam:ListMFADevices",
              "iam:ListVirtualMFADevices",
              "iam:ResyncMFADevice",
              "sts:GetSessionToken"
          ],

```

Which as an explicit Deny will enforce MFA not only for console logins but also for access keys on the command line.  @RonWilliams and I already have this policy in place on our production account. 

I don't think we can do this yet in terraform, but instead would have to run something like this for each of our accounts:

```
aws iam attach-group-policy
          --group-name Administrators
          --policy-arn arn:aws-us-gov:iam::{aws-account-number}:policy/self-managed-credentials
```

Once this is in place, we'd need to use `aws-vault` which is already described in https://cloud.gov/docs/ops/secrets/.

## Hypothesized benefit(s)/why:

See #1262 

## Potential metrics

Enforce with AWS InSpec running in Concourse based on https://github.com/cloud-gov/cg-compliance/audit 

## Implementation steps - in rough order...

- [x] Run the Inspec profile at https://github.com/cloud-gov/cg-compliance/blob/master/audit (link not working until merged). It should fail.
- [x] Run `aws iam attach-user-policy --user-name your.self --policy-arn arn:aws-us-gov:iam::{aws-account-number}:policy/self-managed-credentials`
- [x] Run inspec again. It should fail because you're not using MFA with your access keys
- [x]  Install and configure aws-vault per https://cloud.gov/docs/ops/secrets/#aws-credentials
- [x] Run inspec again. It should fail the same way it did the first time.
- [x] Detach policy from your self
- [x] Update any documentation that the team will need for using aws-vault 
- [x] Notify all admins and attach policy to all admins for all accounts
           ```
            aws iam attach-group-policy
              --group-name Administrators
              --policy-arn arn:aws-us-gov:iam::{aws-account-number}:policy/self-managed-credentials
            ```
- [x] Run InSpec again - It should pass.
- [x] ~Bonus: Make inspec work for all our accounts~
- [x] ~Make a ticket to run InSpec continually in Prometheus or Concourse~

**Comment by ccostino** [comment]
@pburkholder and I paired on this a bit today and got as far as testing the flow out for working with `aws-vault` and attaching MFA in the command line for short lived tokens.  I have [a PR in place for updating the documentation](https://github.com/cloud-gov/cg-site/pull/1661) to help others configure this for themselves and could use some :eyes: to review and test the steps.

Also, please consider this the notice for @cloud-gov/platform-ops that this is coming and the self-managed credentials policy will be applied in the near future, which means you'll need MFA on all of your accounts (which should already be there!) and `aws-vault` installed and configured on your machine.

@pburkholder, did I miss anything or mis-state anything?  Thanks again for your help today!

**Comment by pburkholder** [comment]
Folks - please check off the box below when you are ready for access-key level MFA to be turned on. Once we start enforcing this, you can only effectively use `aws` or other AWS CLI tools with `aws-vault`. This will be enforced on ALL of our accounts. You can check the box _before_ you have aws-vault set up, as long as you're ready to set that up next time you're wanting to work with that account. 

* [ ] @apburnes 
* [ ] @bengerman13 
* [ ] @ccostino 
* [ ] @ChrisMcGowan 
* [ ] @mheadd 
* [ ] @pburkholder 
* [ ] @spgreenberg 
* [ ] @tammersaleh 
* [ ] @soutenniza 
* [ ] @RonWilliams 
* [ ] @eddietejeda

**Comment by pburkholder** [comment]
@ccostino Ugh, our commercial accounts are going to need some reorganizing for this to work. I think we should look at some Terraforming to get this right.  Maybe we should pair on this again.

**Comment by pburkholder** [comment]
I need  the `self-managed-credentials` policy associated with my user in AWS E-W, as right now I'm not able to create an access key pair in the console. 

Can you create that policy and associate it with my user in that account, @ccostino ?

**Comment by ccostino** [comment]
@cloud-gov/platform-ops, please note in this issue whether you already have MFA setup or are comfortable setting that up after this is in place.  I also manually created the [`self-managed-credentials`](https://github.com/cloud-gov/cg-provision/blob/master/terraform/modules/iam_role_policy/self_managed_credentials/policy.json) policy with @pburkholder in the commercial account to get things moving forward.

I think in the future we'll want this in Terraform but I am not sure of the best path forward here.  Is there any guidance or previous work done that I can reference to see how to add this in on the commercial side so that we have parity between the commercial and GovCloud accounts?  Or is there another approach that we should be taking here?

We're not going to apply the rest of this work in the commercial account yet because we'd have to manually apply more IAM changes, and we'd like feedback on this approach first.  Thanks!

**Comment by spgreenberg** [comment]
The approach makes sense to me. If we move IAM to terraform, applying a consistent policy across govcloud and commercial becomes possible. This is even more important when we finally split our environments across different accounts.

**Comment by soutenniza** [comment]
@ccostino For modifying terraform, it looks like you would just need to add something similar to [iam.tf](https://github.com/cloud-gov/cg-provision/blob/f7674f7efb33d494952566a025a620604955311f/terraform/stacks/tooling/iam.tf) to the `external` stack and it would apply to commerical

**Comment by ccostino** [comment]
Thank you, @spgreenberg and @soutenniza!  That helps us.

**Comment by ccostino** [comment]
The remaining bits of this work on the commercial are now captured in https://github.com/cloud-gov/product/issues/1369 - thanks @pburkholder for all of your help on this!
