### ISSUE TITLE
Develop C-Level Cloud Adoption Playbook

### ISSUE THREAD

**Issue by mheadd** [cloud-gov/product#1372]
In order to communicate the benefits of cloud adoption generally and cloud.gov specifically, the business unit would like a brief strategy document to use in conversations with agency CIO/CTOs.

## Security considerations
N/A

## Tasks
Draft document - https://docs.google.com/document/d/1KTnWt0KTlvw06blAN_iG-wDgkB9dSZrMRtMgpYHjSTw/edit
* [x] Review any similar materials that have been developed in other parts of TTS
* [ ] Develop initial draft of playbook
* [ ] Socialize draft with team for feedback / edits
* [ ] Incorporate edits / changes
* [ ] Share final version with @eddietejeda for approval

**Comment by wz-gsa** [comment]
@sknep requested I mention this is being closed due to stale issue / security audit.
