### ISSUE TITLE
Deprecate cloud.gov shared database environment (Aug 31, 2022)

### ISSUE THREAD

**Issue by RonWilliams** [cloud-gov/product#1391]
With the completion of [Enable t2/t3 micro instance plans for PostgreSQL and MySQL in AWS RDS](https://github.com/cloud-gov/aws-broker/pull/81), we should notify users that the `shared-psql` and `shared-mysql` database services will be deprecated. 

## Security considerations
Improves security by improving isolation of cloud.gov database users. 

## Tasks

* [x] [Draft Deprecation Notice](https://github.com/cloud-gov/product/issues/1399)
* [x] Send notices required per [cloud.gov Deprecation Policy](https://cloud.gov/docs/technology/responsibilities/#deprecation-policy)
* [x] [Enable db.t2/t3.micro instances for sandbox accounts](https://github.com/cloud-gov/product/issues/1400)
* [x] Identify and migrate databases that should be retained (if any)

**Comment by RonWilliams** [comment]
@karareinsel: Thoughts on assigning to @onelittlebecca and pairing with @ccostino?

**Comment by karareinsel** [comment]
I think it's a great opportunity for @onelittlebecca to pair with @ccostino . Let's see what gets prioritized in next Monday's prioritization meeting - we currently have 8 stories in the backlog and 7 stories in triage.

**Comment by ccostino** [comment]
Sounds good to me, thank you!

**Comment by pburkholder** [comment]
This may severely hamper the ability of some users to do integration tests given the time it takes to spin up a shared instance (depending on their use case). I also think we should consider the relative priority of this compared to other compliance/security related issues we have to attend to. 

Have we reached out to shared DB users to determine if micro DBs will suit their needs?

**Comment by onelittlebecca** [comment]
Sounds good to me as well.

**Comment by RonWilliams** [comment]
Given the opaque nature of allocating costs associated with the shared database instance, it is necessary to migrate towards independent micro instances. The shared database has also proven to be difficult to upgrade and has limited scale as we enroll more users. Ongoing operation of the unique and limited use environment also imposes a cost burden greater than the value that cloud.gov can quantifiably derive and deliver. 

Deprecation of the shared database instance and subsequent notifications throughout the process permit cloud.gov to encourage users to migrate to appropriate replacement instances. For paid customer workloads requiring greater than a micro instance, we will continue to provider larger instance types under our paid accounts.

**Comment by ccostino** [comment]
We're waiting to hear back from AWS support to see what options we have with encryption at rest for MySQL, as the `db.t2.micro` instance class does not support it.

**Comment by ccostino** [comment]
@pburkholder, as a part of announcing any deprecation of the shared instances we should definitely check on customer uses cases as well, but I'd think for integration testing that'd be done via local tests (either with something like a SQLite database or creating a test database in a local/Docker-ized PostgreSQL or MySQL server) or a CI/CD system (e.g., CircleCI), which would spin up a separate instance itself as a part of the process.

Furthermore, anything that is not run locally is going to have to wait for something to be spun up regardless.  If integration testing is being done in a cloud.gov space (e.g., a customer's dev space), the database would already be provisioned and it would just be a matter of new temporary tables being created and dropped, not waiting for the instance itself to be provisioned.  If someone is doing that, I'd encourage them not to; keep a micro or small instance running in the dev space for that purpose.

Theoretically, the only disruptive point in this should just be a matter of switching folks currently using the shared instances to the dedicated ones, and we have [a process](https://cloud.gov/docs/services/relational-database/#exporting-a-database) that can assist with that.  It's not written on that page explicitly (at least not yet), but a customer can restore a backup into a newly provisioned instance ([FEC does this](https://github.com/fecgov/fec-cms/wiki/Backup-or-Restore-Wagtail-PostgreSQL-database-in-dev,-staging,-or-production)), or we could take care of this on our side if that makes more sense.

**Comment by ccostino** [comment]
I followed up with AWS Support again regarding our RDS questions.

**Comment by pburkholder** [comment]
So it seems that there are fewer shared database creation events than I expected, and it doesn't seem like anyone is repeatedly creating databases as part of test suite. I did a lot of DB create/deploy when I was trying to get Drupal8 to work as a repeatable project, so I expect the pain, if any, will fall on our team. 

```
"2020-06-15T20:47:31Z","peter.burkholder@gsa.gov","audit.service_instance.create","cf-spring-db","3a8e624f-ba5a-4435-8fa4-ee955b103bae"
"2020-06-16T14:16:43Z","rebecca.goodman@gsa.gov","audit.service_instance.create","database","3a8e624f-ba5a-4435-8fa4-ee955b103bae"
"2020-06-17T18:43:52Z","elwthompson@fdic.gov","audit.service_instance.create","pfadatamanagerdb","64a259ed-01ab-4cdb-ace3-14fc7bde4ab6"
"2020-06-17T19:48:11Z","tharalla.naveen@epa.gov","audit.service_instance.create","nsteps-wpdb-service","3a8e624f-ba5a-4435-8fa4-ee955b103bae"
"2020-06-18T14:00:07Z","joseph.krzystan@gsa.gov","audit.service_instance.create","crt-jbk","64a259ed-01ab-4cdb-ace3-14fc7bde4ab6"
"2020-06-18T15:26:55Z","tharalla.naveen@epa.gov","audit.service_instance.create","nsteps-wpdb-service","3a8e624f-ba5a-4435-8fa4-ee955b103bae"
"2020-06-18T21:13:37Z","peter.burkholder@gsa.gov","audit.service_instance.create","sample-app-db","3a8e624f-ba5a-4435-8fa4-ee955b103bae"
"2020-06-19T00:24:02Z","mgottumukkala@fdic.gov","audit.service_instance.create","jasperdb","3a8e624f-ba5a-4435-8fa4-ee955b103bae"
"2020-06-22T15:21:21Z","mark.headd@gsa.gov","audit.service_instance.create","database","3a8e624f-ba5a-4435-8fa4-ee955b103bae"
"2020-06-22T15:49:53Z","broker-deployer","audit.service_instance.create","rds-smoke-tests-shared-psql","64a259ed-01ab-4cdb-ace3-14fc7bde4ab6"
"2020-06-22T15:49:53Z","broker-deployer","audit.service_instance.create","rds-smoke-tests-shared-mysql","3a8e624f-ba5a-4435-8fa4-ee955b103bae"
"2020-06-22T19:40:26Z","theodros.desta@gsa.gov","audit.service_instance.create","sin-sql","64a259ed-01ab-4cdb-ace3-14fc7bde4ab6"
"2020-06-22T19:40:43Z","theodros.desta@gsa.gov","audit.service_instance.create","sin-td-sql","64a259ed-01ab-4cdb-ace3-14fc7bde4ab6"
"2020-06-23T13:33:45Z","rebecca.goodman@gsa.gov","audit.service_instance.create","database","3a8e624f-ba5a-4435-8fa4-ee955b103bae"
"2020-06-24T22:13:46Z","broker-deployer","audit.service_instance.create","rds-smoke-tests-shared-psql","64a259ed-01ab-4cdb-ace3-14fc7bde4ab6"
"2020-06-24T22:14:17Z","broker-deployer","audit.service_instance.create","rds-smoke-tests-shared-mysql","3a8e624f-ba5a-4435-8fa4-ee955b103bae"
"2020-06-26T19:11:45Z","mark.headd@gsa.gov","audit.service_instance.create","my-test-db-service","3a8e624f-ba5a-4435-8fa4-ee955b103bae"
"2020-07-02T19:26:57Z","racwright@fdic.gov","audit.service_instance.create","efx-sql","3a8e624f-ba5a-4435-8fa4-ee955b103bae"
"2020-07-06T22:40:39Z","jknowles@usbr.gov","audit.service_instance.create","database","3a8e624f-ba5a-4435-8fa4-ee955b103bae"
"2020-07-07T15:12:10Z","peter.burkholder@gsa.gov","audit.service_instance.create","dbtest1","3a8e624f-ba5a-4435-8fa4-ee955b103bae"
"2020-07-07T15:18:35Z","peter.burkholder@gsa.gov","audit.service_instance.create","psqltest1","64a259ed-01ab-4cdb-ace3-14fc7bde4ab6"
```

P.S.: I'd been meaning to understand our audit event logging better, so this was 15m well spent in that realm.

**Comment by pburkholder** [comment]
That said, I think it would be a good idea to reach out to customers that we know have been instantiating shared plans to determine how the deprecation would impact them. I still think there are cost and security assumptions here that still merit a second look, but if the door to questioning this deprecation has closed, then I'll I won't go into those here.

**Comment by karareinsel** [comment]
@RonWilliams will you break this story out into smaller stories?

**Comment by pburkholder** [comment]
To do a new audit of shared database creation:

```
sh audit.sh | egrep '3a8e624f-ba5a-4435-8fa4-ee955b103bae|64a259ed-01ab-4cdb-ace3-14fc7bde4ab'
```

[Here's a gist of audit.sh](https://gist.github.com/pburkholder/1487ee78da3de11ea49bbcd49984e1cf)

**Comment by pburkholder** [comment]
```
sh audit.sh | egrep '3a8e624f-ba5a-4435-8fa4-ee955b103bae|64a259ed-01ab-4cdb-ace3-14fc7bde4ab' | awk -F, '{print $2}' | grep '@' | sort -u
```
results in 2 FDIC users, 2 GSA users, 1 EPA user, and 4 contractors

**Comment by jfredrickson5** [comment]
Overall steps to disable access and eventually delete the plans and databases:

**Disable the plans**
- [x] Remove content from cg-site (https://github.com/cloud-gov/cg-site/pull/1919)
- [ ] Disable services:
  ```
  cf disable-service-access aws-rds -b aws-broker -p shared-psql
  cf disable-service-access aws-rds -b aws-broker -p shared-mysql
  ```

**Delete existing instances using the shared plans**
- [ ] Customer communications
- [ ] Figure out if any instances need to be preserved
- [ ] Delete instances
  ```
  # Get info on all shared RDS instances
  cf curl "/v3/service_instances?service_plan_names=shared-psql" > shared-psql-instances.json
  cf curl "/v3/service_instances?service_plan_names=shared-mysql" > shared-mysql-instances.json
  
  # Get the instance GUIDs
  jq -r '.resources[].guid' shared-psql-instances.json > shared-psql-instances.txt
  jq -r '.resources[].guid' shared-mysql-instances.json > shared-mysql-instances.txt
  
  # At this point, if any of the instances should be preserved, now would be a good time to look through the list and figure out what needs to stay and what needs to go
  
  # Delete all instances from the two lists
  for guid in `cat cf-dev-shared-mysql-instances.txt cf-dev-shared-psql-instances.txt` ; do cf curl -X DELETE /v3/service_instances/$guid ; done
  ```

**Remove the plans**
- [ ] Remove from broker (https://github.com/cloud-gov/aws-broker/pull/169)

**Remove the infrastructure**
- [ ] Create snapshots of the shared MySQL and PostgreSQL instances
- [ ] Remove RDS databases via Terraform
- [ ] Remove Concourse credentials

**Comment by mogul** [comment]
@rbogle can you put a calendar reminder in for us to nag customers still using this plan every couple weeks?

**Comment by rbogle** [comment]
Yes will do. Have a process to generate the list of owners of remaining Dbs, then bulk email reminders in place

**Comment by CloudEthos** [comment]
@rbogle Has there been any movement on this item?

**Comment by rbogle** [comment]
New ticket will be created to delete existing shared dbs and remove plans
