### ISSUE TITLE
Provide SQL Server service

### ISSUE THREAD

**Issue by mheadd** [cloud-gov/product#1691]
# What we're after

cloud.gov provides a brokered SQL Server service.

## Hypothesized benefit(s)/why:
* We have had requests from customers interested in migrating to cloud.gov to offer a brokered version of SQL Server
* Applications written in .NET are often more tightly coupled with SQL Server, so supporting a brokered version might encourage more system owners to look at migrating .NET applications to the platform.
* Enable faster transition for applications included in the MAX.gov migration effort

## Potential metrics
* New BD leads advanced because of offering this option
* Number of new RDS types created

---
### Further context for those unfamiliar with what we're doing

Currently, cloud.gov offers several different flavors of brokered RDS - PostgreSQL, MySQL and Oracle. SQL Server had been offered at one point in time, but was deprecated due to lack of demand.

### Security considerations
Would require modifications to the AWS broker. Uncertain if adding a new RDS type would intro any new security related issues beyond what are normally assumed for other RDS services. [We will submit an SCR to the FedRAMP JAB reviewers, but they believe this capability can be re-enabled with minimum fuss.](https://github.com/cloud-gov/product/issues/1691#issuecomment-1146492558)

### Notes for implementers

See [this thread in #cg-support](https://gsa-tts.slack.com/archives/C09CR1Q9Z/p1646056910779149), which includes an archaeological dig into the history of the AWS broker code for SQL Server. 

### Related issues/sub-projects

- [ ] cloud-gov/private#992
- [ ] Re-enable SQL Server in the AWS broker
- [ ] Ensure SQL Server instances meet [the CIS standard](https://github.com/mitre/microsoft-sql-server-2017-cis-baseline) (or STIG standards if possible)
- [ ] Re-add SQL server in the RDS service site documentation
- [ ] Announce availability of SQL Server in RDS service and contact previously-interested customers

**Comment by mogul** [comment]
We spoke to the FedRAMP JAB about re-enabling SQL Server as a plan in the cloud.gov RDS broker this week. 

As this change would not impact existing controls, diagrams, etc. and the capability existed previously, they agreed we should be able to re-enable it without full assessment and turn around the approval quickly. 

They asked us to do a write-up in the Significant Change Request (SCR) template and mail it to them to kick that off. We will do that early this coming week.

**Comment by mogul** [comment]
@pburkholder [said](https://github.com/cloud-gov/product/issues/1772#issuecomment-1147901203):
> Might help to demonstrate, with examples like https://github.com/mitre/aws-rds-oracle-mysql-ee-5.7-cis-baseline and https://github.com/mitre/aws-rds-infrastructure-cis-baseline, that our broker churns out CIS benchmarked instances.

We're a little restricted there... Note that: 
- [The most recent CIS benchmark available for SQL Server](https://github.com/mitre/microsoft-sql-server-2017-cis-baseline) is 2017, but it's oriented toward Windows hosts, not AWS RDS.
- There's [a separate 2017 benchmark repository for AWS RDS instances](https://github.com/mitre/aws-rds-microsoft-sql-server-2017-cis-baseline), but it's new and empty.
- There's [another AWS RDS-specific repository](https://github.com/mitre/aws-rds-microsoft-sql-server-2014-instance-stig-baseline), but for 2014.

> Do they want SQL Server 2019 or 2016 or ...?

Here's the full [AWS RDS SQL Server version list](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_SQLServer.html#SQLServer.Concepts.General.VersionSupport). I'd like to only support the latest versions, but that's a good question for @wesley-dean-gsa and @lanierkyle. Will prompt them to post here.

**Comment by lanierkyle** [comment]
SQL Server 2012 would be a marketable option for cloud.gov considering it is backwards compatible for earlier versions, and we have two partners specifically using 2012.  Another partner is on 2014, with two additional partners using 2019. For each major version mentioned (2012, 2014, 2019), would kindly suggest the latest minor version and latest RDS API engine version.

Should a partner not be on the latest minor version, it would not be unreasonable on our side to encourage and assist their effort towards healthy database upkeep.

**Comment by mogul** [comment]
Can anyone comment as to the overall status of this epic, given work in the most recent quarter?

**Comment by pburkholder** [comment]
No real progress. I did some exploratory work on determining the CIS benchmarks for this and how to evaluate compliance using Inspec and MITRE's work.
