### ISSUE TITLE
Meet EO M-21-31 requirements for log retention - 2022-08-27 EL1 deadline

### ISSUE THREAD

**Issue by mogul** [cloud-gov/product#1726]
# What we're after
cloud.gov operators and customers meet [M-21-31](https://www.whitehouse.gov/wp-content/uploads/2021/08/M-21-31-Improving-the-Federal-Governments-Investigative-and-Remediation-Capabilities-Related-to-Cybersecurity-Incidents.pdf) EL1 requirements before the 2022-08-27 deadline.

## Hypothesized benefit(s)/why:
* cloud.gov operators are in good standing with FedRAMP
* cloud.gov customers are in good standing with their own agencies

## Potential metrics
* [a metric that might be useful in measuring progress/completion]
* [another metric]

---
### Further context for those unfamiliar with what we're doing

See [Presidential Memorandum M-21-31](https://www.whitehouse.gov/wp-content/uploads/2021/08/M-21-31-Improving-the-Federal-Governments-Investigative-and-Remediation-Capabilities-Related-to-Cybersecurity-Incidents.pdf).

### Security considerations
[note any potential changes to security boundaries, practices, documentation, risk]

### Notes for implementers

From "Section II: Agency Implementation Requirements" in the memorandum...

Agencies must immediately begin efforts to increase performance in accordance with the
requirements of this memorandum. Specifically, agencies must:
- Within 60 calendar days of the date of this memorandum, assess their maturity against
the maturity model in this memorandum and identify resourcing and implementation gaps
associated with completing each of the requirements listed below. Agencies will provide
their plans and estimates to their OMB Resource Management Office (RMO) and Office
of the Federal Chief Information Officer (OFCIO) desk officer.
- Within one year of the date of this memorandum, reach EL1 maturity.
- Within 18 months of the date of this memorandum, achieve EL2 maturity.
- Within two years of the date of this memorandum, achieve EL3 maturity.
- Provide, upon request and to the extent consistent with applicable law, relevant logs to
the Cybersecurity and Infrastructure Security Agency (CISA) and Federal Bureau of
Investigation (FBI). This sharing of information is critical to defend Federal information
systems.
- Share log information, as needed and appropriate, with other Federal agencies to address
cybersecurity risks or incidents

### Related issues/sub-projects

Ongoing

- [x] https://github.com/cloud-gov/product/issues/2112

PI 31.1

- [x] https://github.com/cloud-gov/product/issues/2122
- [x] https://github.com/cloud-gov/product/issues/2123

PI 31.2

- [x] https://github.com/cloud-gov/product/issues/2149
- [x] https://github.com/cloud-gov/product/issues/2150
- [ ] https://github.com/cloud-gov/product/issues/2151

PI 31.3

- [x] https://github.com/cloud-gov/product/issues/2130
- [x] https://github.com/cloud-gov/product/issues/2126
- [x] https://github.com/cloud-gov/product/issues/2125

PI 31.4

- [x] https://github.com/cloud-gov/product/issues/2124
- [x] https://github.com/cloud-gov/product/issues/2132
- [x] https://github.com/cloud-gov/product/issues/2127

PI 31.5 

- [x] https://github.com/cloud-gov/product/issues/2134

IP sprint

- [x] https://github.com/cloud-gov/product/issues/2152
- [x] https://github.com/cloud-gov/product/issues/2153

Nice additions:

- Polish and publish [example code for customers who need to ship logs to their own SOC](https://github.com/GSA/datagov-logstack)

**Comment by pburkholder** [comment]
I've tried to aggregate the requirements, and how we'll meet them in the [M-21-31 requirements spreadsheet](https://docs.google.com/spreadsheets/d/1t3t6Ou6E-1YGfd-nkdJJXl0nO3zPVbxkxtdNDR3rpUo/edit#gid=0)

As I've said elsewhere:
> [M-21-31 ](https://www.whitehouse.gov/wp-content/uploads/2021/08/M-21-31-Improving-the-Federal-Governments-Investigative-and-Remediation-Capabilities-Related-to-Cybersecurity-Incidents.pdf)is making my head hurt.  I don't see how it works for [cloud.gov](http://cloud.gov/), or  for SaaSes like SmartSheets or highly-abstracted PaaSes like Salesforce? Does SmartSheet/Salesforce ship logs to GSA and other agencies? Or do they just attest to having sufficient capabilities per the memo? M-21-31 seems to be written with just desktop systems, IaaS and datacenters in mind, and lot of how responsibilities break down are hard to comprehend for systems that aren’t in that mold.

In that vein, I haven't seen any guidance for how M-21-31 should be interpreted in under the cloud's "Shared responsibility" model. While we are working to leverage GSA's SOC for some of these, it's not clear where we're the agency, or our customer is. 

Anyhow, we should be asking more questions of:
* The FedRAMP PMO
* : ofcio@omb.eop.gov, per: " Policy Assistance: Address all questions or inquiries regarding this memorandum to the OMB Office of the: Federal Chief Information Officer (OFCIO) 
* CISA, since under the memo their responsible for tools and assessment.

**Comment by pburkholder** [comment]
Some useful language for inquiries for the time being:
> Thanks for your inquiry. [Cloud.gov](http://cloud.gov/) already met most of the requirements of M-21-31 for EL1 at the time the memo was released in last August. We are on track to close the few remaining requirements, and are consulting with CISA, OMB, and FedRAMP on how these responsibilities fall into the cloud “shared responsibility” model.

**Comment by mogul** [comment]
It looks like nearly all of the linked issues are now closed. Can anyone comment as to the overall status of this epic, given work in the most recent quarter?

**Comment by mogul** [comment]
While there are still a couple close-out issues on the Team project board, I'm going to move this epic from `Now` to `Recent` as a reflection that it's basically behind us and customers are deriving the benefit.

We should be sure to announce these changes in the next newsletter!
