### ISSUE TITLE
Transfer Pages repositories from 18f to cloud-gov GH organization

### ISSUE THREAD

**Issue by davemcorwin** [cloud-gov/product#2077]
- [x] 18f/federalist-uswds-jekyll
- [x] 18f/federalist-uswds-gatsby
- [x] 18f/federalist-proxy-edge (archived)
- [x] 18f/federalist.18f.gov
- [x] 18f/federalist-proxy
- [x] 18f/federalist-infra
- [x] 18f/federalist-garden-build
- [x] 18f/federalist-builder
- [x] 18f/federalist
