### ISSUE TITLE
Complete transition of Federalist->cloud.gov Pages

### ISSUE THREAD

**Issue by mogul** [cloud-gov/product#2080]
# What we're after

By (approximate target) mid-September 2022 Federalist should be completely rebranded to cloud.gov Pages and operate only within the cloud.gov JAB boundary, and customers should be ready to transition (if not already migrated).

## Hypothesized benefit(s)/why:
* [a stakeholder who will benefit and how]
* [benefit 2]
* [another feature this would enable]

## Potential metrics
* [x] How many places Federalist appears in public-facing materials (--> 0)
* [x] How many users are using GitHub for a18n (--> 0)
* [ ] How many sites are outside of an organization (--> 0)

---
### Further context for those unfamiliar with what we're doing

[add any background context necessary to understand what this feature is about or why it's needed.]

[list what you would expect to the feature to include in more detail. talk about any critical workflows. For example "cloud.gov should allow users to request and view the options available for an SQS service, create an SQS service instance for their Cloud Foundry space, and associate/disassociate the SQS service instance with one or more apps. When the Cloud Foundry service instance is deleted, the SQS service that was instantiated upon service creation and any credentials issued for bind operations should be deleted as well.""]

### Security considerations
[note any potential changes to security boundaries, practices, documentation, risk]

### Notes for implementers

- [Pointers to relevant languages, components, frameworks, prior art/examples, user research, mockups, etc.]
- [a technical sketch if we're confident of how to approach implementation]
- [Example: "We need to create a new broker. Get familiar with [the docs](https://docs.cloudfoundry.org/services/overview.html). [Broker API](https://github.com/pivotal-cf/brokerapi) is a good starting point. Implementation can be done with any AWS account; no access to existing cloud.gov infrastructure should be needed to develop or demo it. The behavior can be demonstrated via exercise of the broker’s REST APIs.]

### Relevant repositories

Keepers to migrate:

- [x] 18f/federalist
- [x] 18f/federalist-builder
- [x] 18f/federalist-proxy
- [x] 18f/federalist-garden-build

Already in cloud.gov:
- [x] cloud-gov/cg-deploy-cf (some IaC/deployment in it; UAA client provision)
- [x] cloud-gov/cg-provision (IaC for DNS)
- [x] cloud-gov/cg-report-federalist-s3 (S3 monitoring/reporting to support Pages)
- [x] cloud-gov/pages-mailer
- [x] cloud-gov/federalist-uswds-jekyll
- [x] cloud-gov/federalist-uswds-gatsby
- [x] cloud-gov/federalist-uswds-11ty

Deprecating:

- [x] 18f/pages-redirect
  - TTS nginx-proxy target for DNS CNAMEs (should be owned by TTS)
- [x] cloud-gov/federalist-proxy-edge 
  - already archived, not in use
- [x] cloud-gov/federalist.18f.gov
  - There's an existing cg-site branch that incorporates a bunch of this 
- [x] 18f/federalist-infra 
  - Terraform for AWS stuff that's now provided by cloud.gov under Pages; could be repurposed to use the CF provider in future.
- [x] github.com/federalist-users org 
  - controls a18n for Federalist, going away in favor of UAA
  - Also has a OAuth app, but there's a replacement coming up in cloud-gov

### Deployments

- [x] gsa-18f-federalist org and spaces - migrating in place, should probably be renamed
  - [x] email egress space (proxy to cloud.gov SMTP services on internal route)

### Related issues/sub-projects

- [x] There is a bunch of stuff in [this document](https://docs.google.com/document/d/1xVn9c9c4GaV-YSfSgaUOFTEwej8If0XH9d7mNq-PWVM/edit) that should be detangled and put into the list below.
- [x] #2093
- [x] [#2097](https://github.com/cloud-gov/product/issues/2097)
- [x] #2087
- [x] #2086
- [x] #2088
- [x] #2089
- [x] #2090 
- [x] #2091
- [x] #2092
- [x] #2093 
- [x] #2083 
- [x] https://github.com/18F/federalist/issues/3423
- [x] https://github.com/cloud-gov/product/issues/2090
- [x] #2094

**Comment by mogul** [comment]
It looks like nearly all of the linked issues are now closed. Can anyone comment as to the overall status of this epic, given work in the most recent quarter?

**Comment by mogul** [comment]
OK. Going to leave this Epic in the `Now` column. During planning, let's not forget to account for some of our capacity being drained off by support here.

**Comment by apburnes** [comment]
Complete.
