### ISSUE TITLE
Send out announcement about Pages transition

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/product#2093]
In order to inform our customers about the start of the transition. We need to send out emails, add documentation the marketing site, add news post to cloud.gov, and add links to the comms from the app.

## Acceptance Criteria
- [x] Finalize draft via [pages comms working doc](https://docs.google.com/document/d/1QL_rK41xOA8uh-l9od2H5FwOz1biO82vaCTWwUzPNmY) and/or [other doc](https://docs.google.com/document/d/1BUNYbHsXBorkM3kSBwnnQHEm9dphbFLFsp78S5LHwFg)
- [x] Send out transition info in cg newsletter
- [x] ~Send email to current customer list~ (transitioned to #2154)
- [x] ~Add news post to cloud.gov about Pages~ (transitioned to #2155)
- [x] ~Add docs in the marketing site~ (transitioned to #2156)
- [x] ~Update banner with links in the pages/federalist app~ (transitioned to #2156)

## Security Considerations
Needed to complete SCR

**Comment by apburnes** [comment]
Moving into ongoing since this will progress over the next month.

**Comment by apburnes** [comment]
Completed and broken out into smaller issues.
