### ISSUE TITLE
Outline the goals for a Pages compliance research spike/epic

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/product#2168]
In order to run a Pages compliance research spike , we want to outline the goals for a sprint of work devoted to understanding, planning, and strategizing on the future needs of the compliance and ATO process for Pages customer sites both inside and outside of GSA.

## Acceptance Criteria
* [ ] Talk with customers in and outside of GSA to outline their specific ATO process
* [ ] Identify possible customer CISO outside of GSA that would be willing to work with Pages to authorize the platform for their agency
* [ ] Identify the NIST controls Pages covers for both FISMA Low and Moderate systems
* [x] Finalize a Customer Responsibility Matrix
* [x] Identify tooling to automate the population of NIST controls
* [ ] Create an epic issue with findings for a future sprint
--- 

## Security considerations
Informs a customer of the post Pages world.

## Implementation sketch
* [ ] Create a document with the research spike goals
* [ ] Aggregate current and created artifacts in the doc
* [ ] Review the doc to outline the epic issue
* [ ] Create the epic issue

**Comment by pburkholder** [comment]
@apburnes Should we just use this issue to cover the concerns that Ashley M raised today?

**Comment by apburnes** [comment]
Makes sense to me. We will just update the description to re-align the issue tasks.

**Comment by apburnes** [comment]
Closing due to stalenesss
