### ISSUE TITLE
Automation for maintaining / updating Service Broker Catalogs.

### ISSUE THREAD

**Issue by rbogle** [cloud-gov/product#2191]
In order to keep our service broker plans up to date with AWS changes and customer needs, we want to automate data gathering and reportinofferings/versionsinstance types, AWS service offerings / versions, as well as customer service instance plans/versions.

## Acceptance Criteria
* [ ] GIVEN a particular service broker type
  AND its catalog of current plans
  WHEN we have our quarterly tech review
  AND want to assess the availability and deprecations of AWS offerings related to current service broker plans
  THEN a script can be run manually or by pipeline
  AND generate a report of AWS-supported service versions (eg MySQL x.x) their compatible instance types, and a list of all 
  provisioned versions in AWS correlated with the service broker instance id, org, space, and plan type. 

--- 

## Security considerations
None

## Implementation sketch
see existing scripts in cg-scripts repository in audit for some prior art. 
* [] develop script/tool using aws cli to query a service for current compatible versions and instances
* [] develop script/tool using cf cli /api to query cf for service broker plan instances and related metadata
* [] develop method for formatting and delivering data from above tools.
