### ISSUE TITLE
Enable AWS Config for GovCloud

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/product#2242]
## Background

See the [Security: Monitoring & Alerting ADR](https://github.com/cloud-gov/internal-docs/blob/main/docs/ADRs/ADR-0010-aws-security-monitoring-alerting.md) for background on this feature

## Prerequisites

- https://github.com/cloud-gov/product/issues/2342
- https://github.com/cloud-gov/product/issues/2343

## Acceptance criteria

- [x] AWS Config is enabled in all accounts of the GovCloud AWS Organization
- [x] AWS Config is managed from the delegated administrator (security account) of the GovCloud AWS Organization
- [x] From the delegated administrator (security account), we can see the results aggregated for all accounts in the organization

## Implementation

1. Update the `cg-provision` repo to include Terraform code that is deployed in all of the GovCloud organization accounts
    - Reference for all accounts in the organization can be found here: <https://github.com/cloud-gov/aws-admin/blob/main/stacks/gov/sso/main.tf#L21>
1. Update the `cg-provision` code to create the following resources in all GovCloud accounts:
    - AWS Config settings: <https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/config_configuration_recorder>
    - AWS Config delivery channel (should use an S3 bucket): <https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/config_delivery_channel>
    - AWS Config rules: <https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/config_config_rule>
1. Add code in `cg-provision` to create the AWS Config Aggregator in the GovCloud delegated administrator account (security account)
    - <https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/config_configuration_aggregator>
