### ISSUE TITLE
Decide how to implement Shield Advanced in the External Domain Broker

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/product#2323]
* [ ] Decide if we add Shield Advanced to the current CDN plan or add a new plan. 
  * We try to require as little as possible from our customers, so if possible, adding it automatically would be better. However, that may not be possible. Assess if there is a risk of false positives that the customer would need to assume themselves, and if the period of time where Shield Advanced takes a baseline of traffic requires any interaction from the customer. 
* [ ] Model expected cost based on Shield Advanced egress traffic pricing and document it somewhere.
* [ ] Create an ADR to document the decision.

**Comment by markdboyd** [comment]
Handled by https://github.com/cloud-gov/internal-docs/pull/197
