### ISSUE TITLE
Build and deploy logging platform for tooling environment

### ISSUE THREAD

**Issue by rbogle** [cloud-gov/product#2364]
In order to monitor and observe our tooling environemtn, we want to replicate the logs-platform deployment in tooling.

## Acceptance Criteria
* [ ] running log-platform deployment in tooling env. 
* [ ] logs from concourse ship to this logging platform
* [ ] logs from opsUAA ship to this logging platform
* [ ] logs from prometheus ship to this logging platform
* [ ] logs from concourse-credhuub ship to this logging platform
* [ ] logs from grafana ship to this logging platform
* [ ] logs from doomsday ship to this logging platform
* [ ] logs from any other deployment infrastructure service ship here

--- 

## Security considerations
 this improves our auditability and logging for the control-plane services of the platform across all environments

## Implementation sketch
[TBD resources and links
* [ ] new logs-platform deployment like prod,staging,env in tooling
* [ ] configure tooling service to ship logs to logs-tooling.
