### ISSUE TITLE
Update all TF and Bosh deployments to use gp3 volumes for EC2 

### ISSUE THREAD

**Issue by rbogle** [cloud-gov/product#2376]
In order to reduce costs, we want to migrate all of our EC2 instances currently using gp2 to gp3

## Acceptance Criteria
* [ ] all ec2 instances running will use gp3 by default.

--- 

## Security considerations
None

## Implementation sketch
[links to background notes, sketches, and/or relevant documentation
* [x] identify all terraform EC2 deployments and change parameter to gp3
* [x] identify all bosh deployments and change parameter to gp3

**Comment by markdboyd** [comment]
Current use of gp2 volumes:

https://github.com/search?q=org%3Acloud-gov+NOT+is%3Aarchived+%22gp2%22+&type=code
