### ISSUE TITLE
Report on crypto modules for post-quantum cryptography M-23-02 - due 2023-01-11

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#2377]
In order to satisfy FedRAMP® and OMB, we need to study the reference memo and report accordingly.

## Message from FedRAMP
---
On November 18, 2022, the Office of Management and Budget (OMB) released Memo 23-02, “Migrating to Post-Quantum Cryptography” (the Memo). The Memo states the following: 

> As outlined in [NSM-10](https://www.whitehouse.gov/briefing-room/statements-releases/2022/05/04/national-security-memorandum-on-promoting-united-states-leadership-in-quantum-computing-while-mitigating-risks-to-vulnerable-cryptographic-systems/), the threat posed by the prospect of a cryptanalytically relevant quantum computer (CRQC)5 requires that agencies prepare now to implement post-quantum cryptography (PQC). Once operational, a CRQC is expected to be able to compromise certain widely used cryptographic algorithms used to secure Federal data and information systems. Additionally, agencies must remain cognizant that encrypted data can be recorded now and later decrypted by operators of a future CRQC. 

### ACTIONS REQUIRED

In consultation with the Joint Authorization Board (JAB) and OMB, FedRAMP emphasizes that Cloud Service Providers (CSPs) who maintain federal information fall within the scope defined by the Memo. Therefore, we request that you (1) review the Memo and (2) [upload responses, in the attached template](https://content.govdelivery.com/attachments/USGSA/2022/12/19/file_attachments/2358929/OMB_M_23-02_CSP%20Template_v1.0.xlsx), to the incident response folder in your respective FedRAMP secure repository. Please upload responses by 11:59 PM Eastern Daylight Time on January 11, 2023.

When these actions are complete, we request that you:

* Email all agency customer Authorizing Officials (or ISSO) with notification of the completed action
* Email your JAB point of contact (POC) with notification of the completed action
* Email the FedRAMP PMO with notification of the completed action at [info@fedramp.gov](mailto:info@fedramp.gov) using the following convention for your subject line: [CSP NAME | Package ID] - Response to Memo M-23-02 
* Upload a copy of your Email notifications to the incident response folder in your respective FedRAMP secure repository
If you have any questions, please reach out to [info@fedramp.gov](mailto:info@fedramp.gov).
---

| Image of FedRAMP® message |
|-- |
|  ![image](https://user-images.githubusercontent.com/1211146/211687044-9fcedb7e-01d1-4319-a233-a4d6db868214.png) |

--- 

## Security considerations
These requirements through OMB have been public. The actual report should be considered CUI.

## Implementation sketch
We have earlier reports on crypto modules: https://github.com/cloud-gov/cg-compliance/issues/261 - that can be leveraged here.

## Todos:

- [x]  upload responses to the incident response folder in your respective FedRAMP secure repository by 11:59 PM Eastern Daylight Time on January 11, 2023.
- [x] Email all agency customer Authorizing Officials (or ISSO) with notification of the completed action
- [x] Email your JAB point of contact (POC) with notification of the completed action
- [x] Email the FedRAMP PMO with notification of the completed action at [info@fedramp.gov](mailto:info@fedramp.gov) using the following convention for your subject line: [CSP NAME | Package ID] - Response to Memo M-23-02 
- [ ] Upload a copy of your Email notifications to the incident response folder in your respective FedRAMP secure repository
If you have any questions, please reach out to [info@fedramp.gov](mailto:info@fedramp.gov).

**Comment by pburkholder** [comment]
For question on Applicability: "Applicability. If your organization has identified any CRQC-vulnerable cryptographic systems actively used, fill out the CSP Inventory Tab for each identified instance." I think the answer is "all the systems" since we're not allowed to use any of the post-quantum cryptography yet.
