### ISSUE TITLE
Research AWS Cognito as a possible Shibboleth replacement

### ISSUE THREAD

**Issue by rcgottlieb** [cloud-gov/product#2519]
In order to meet FIPS compliance, we need to ensure our IdP and Service Provider both use FIPS libraries where needed. One possible solution could be to use AWS Cognito in place of Shibboleth.

## Acceptance Criteria
* [ ] We learn whether or not AWS Cognito can be used as an IdP with UAA as the Service Provider
* [ ] We learn if AWS Cognito can replace both Shibboleth and UAA
* [ ] More tickets are created to plan out the next steps that involve AWS Cognito
---

## Security considerations
No change as this is only research, but the end result can be an improvement in security.

## Implementation sketch
[links to background notes, sketches, and/or relevant documentation

* [ ] Research Cognito APIs to see if they can integrate with UAA
* [ ] Research Cognito replacing both Shibboleth and UAA
* [ ] Determine the pricing model for Cognito

**Comment by pburkholder** [comment]
I can't find any evidence from Drive or Slack as to why we didn't pursue Cognito before. It may not have been FedRAMP® authorized. I'd suggest talking to login and/or Alyssa as to whether they recall having dealbreakers with Cognito.

**Comment by pburkholder** [comment]
Be sure to ask AWS if Cognito is itself FIPS 140 validated (not to be confused with FIPS 140 validated endpoints)-- Also get the AWS FedRAMP package https://app.docusign.com/templates/details/06a6e7d8-b602-42aa-9276-b86d8d1a74e4

**Comment by pburkholder** [comment]
I've moved this to "blocked" because we need to marshal resources for the container scanning significant change.
