### ISSUE TITLE
Track 3rd party containers in inventory and any additions or deletions

### ISSUE THREAD

**Issue by banessamoradi** [cloud-gov/product#2538]
**Description:**

- Generate list of containers used in CI
- Maintain status of all containers 
-   Fully hardened and scanned
-   In process
-   Not yet started

- Spreadsheet with status of current containers that is generated by a command in cg-script 

Script should query CI,
and for images in CI
is it in prod (Good)
is it in staging (in Process)
is it absent from ECR (not yet in process)

**Acceptance Criteria:**

- [x] Spreadsheet of currently used containers
- [x] Column with status of containers
- [x] Update documentation with location of spreadsheet and script to query container images

**Comment by dandersonsw** [comment]
https://docs.google.com/spreadsheets/d/1ingzLJtGiosYH0wADDAy7iSlEh49x5na_iaZn_6xfhI/edit#gid=0

**Comment by dandersonsw** [comment]
Moved spreadsheet to the cloud.gov shared container scanning folder: https://docs.google.com/spreadsheets/d/1ingzLJtGiosYH0wADDAy7iSlEh49x5na_iaZn_6xfhI/edit?usp=sharing

Also going to set this ticket as ongoing since we will be modifying the spreadsheet throughout the project

**Comment by dandersonsw** [comment]
Created a PR to update documentation: https://github.com/cloud-gov/internal-docs/pull/136

**Comment by pburkholder** [comment]
I've merged your PR, so closing this. Thanks!
