### ISSUE TITLE
Create Staging environment for testing container hardening

### ISSUE THREAD

**Issue by rcgottlieb** [cloud-gov/product#2549]
As an assurance engineer I need an environment to test out any hardening changes made to the current container scanning pipeline. This is a predecessor to [Demonstrate gating an image on late CVE#2540](https://github.com/cloud-gov/product/issues/2540)  

## Acceptance Criteria
* [ ] When the container scanning pipeline is run, a staging environment is created with two staging tasks, one for concourse and another for s3 hardening.
--- 

## Security considerations
This will aid in improving security as it is a predecessor to a ticket that will add gating
 
## Implementation sketch

* [x] Update terraform in ecr.tf to add the new tasks
* [x] Update pipeline to utilize the new tasks

**Comment by jameshochadel** [comment]
Closing this in favor of scanning containers in pipeline before they are pushed. Will make another ticket to update ADR.
