### ISSUE TITLE
Pages Knowledge Base Article

### ISSUE THREAD

**Issue by Ephraim-G** [cloud-gov/product#2590]
Write an Pages specific knowledge based article regarding deploying an SPA on Pages
```[tasklist]
### Tasks
- [x] Create a simple vanilla REACT JS or Angular JS SPA
- [x] Confirm that all components are configured correctly/ Page works as expected
- [x] Run any e2e tests
- [x] Push it up through the Pages app
- [x] Write up a "how to" KB article while identifying any potential trip ups
- [x] Create PR and have Pages team review
```

**Comment by Ephraim-G** [comment]
closed via https://github.com/cloud-gov/cg-site/pull/2428
