### ISSUE TITLE
Use hardened images for aws-admin pipeline

### ISSUE THREAD

**Issue by jameshochadel** [cloud-gov/product#2626]
```[tasklist]
### Tasks
- [x] registry-image-resource
- [x] slack-notification-resource
- [x] github-pr-resource
- [x] git-resource
- [x] general-task
```
