### ISSUE TITLE
Use hardened images for buildpack-notifier pipeline

### ISSUE THREAD

**Issue by jameshochadel** [cloud-gov/product#2627]
```[tasklist]
### Tasks
- [x] git-resource
- [x] s3-resource
- [x] slack-notification-resource
- [x] github-pr-resource
- [x] replace go resource with git-resource
```
