### ISSUE TITLE
Use hardened images for deploy-aws-broker pipeline

### ISSUE THREAD

**Issue by jameshochadel** [cloud-gov/product#2632]
* [ ] Do this one manually, then think about whether it would be easy to turn into a script. Feel free to make another ticket to actually make the script if it looks easy, but also feel free to keep doing these manually if the automation would take too long. 
```[tasklist]
### Tasks
- [x] Update concourse-task image to general-task
- [x] Update pipeline-tasks repo to use hardened image (https://github.com/cloud-gov/product/issues/2707)
- [x] slack-notification-resource
- [x] s3-resource
- [x] git
- [x] cf
- [x] email-resource
- [x] cron-resource
- [x] registry-image
```

**Comment by banesssa** [comment]
We might have to work this in two parts. @jameshochadel

**Comment by dandersonsw** [comment]
Blocked until we are able to get hardened images for the rest of the resources
