### ISSUE TITLE
Plan NIST 800-53 rev to rev5 implementation

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/product#2698]
Note: This is a copy of https://github.com/cloud-gov/private/issues/767, but in GitHub, "A private repository issue cannot be transferred to a public repository." We've made this public so stakeholders and peers can learn from our experience.

---

In order to meet deadlines for the implementation of FedRAMP® NIST 800-53r5 Moderate baselines, we need to:

```[tasklist]
### Tasks
- [ ] https://github.com/cloud-gov/private/issues/781
- [ ] https://github.com/cloud-gov/private/issues/782
- [ ] https://github.com/cloud-gov/private/issues/783
- [x] Write POA&Ms for some of the 150 changed ones (depending on conditional control selection results)
- [x] Write a new CIS/CRM
- [x] Update SSP with the plan
```

By 10/2
- [x] Update the above based on AWS, etc CRM changes

Estimate: 200 to 300 hours (assuming 3PAO help, else 2x) for the planning, not the implementation

## Security considerations
Compliance requirements, see sub-issues for detailed considerations. 800-53r5 _does_ include security enhancements, especially related to supply-chain security.

This issue tracks compliance, not security, so sharing publicly at a high-level is not a significant risk.

**Comment by pburkholder** [comment]
At our PI planning in late June, we determined we could not simultaneously:
* close existing POA&Ms
* address container scanning requirement
* fix critical technical debt issues, and
* meet the 9/1 FedRAMP deadline for r4 to r5 documentation

So we informed the JAB TRs that we'd be aiming for an 11/1 deadline. This PI has been mostly about a high-level gap analysis and obtaining additional resources for this work.

**Comment by wz-gsa** [comment]
Work completed
