### ISSUE TITLE
Serve dynamic content to a page from a storage service via an API KB

### ISSUE THREAD

**Issue by Ephraim-G** [cloud-gov/product#2798]
In the Pages Proposal document it is stated that one of the features of Pages is that customers are able to serve dynamic content to their site(s) by leveraging storage services within the cloud.gov platform via an API. It would be nice if we had some documentation/a knowledge based article that provided an example or an "How to" regarding this for customers who have use cases for this. 

## Acceptance Criteria
* [ ]  Publish a quality KB article which highlights the capabilities of Pages interfacing with cloud.gov services. 

--- 

## Security considerations
Although this will be non production if making the repository public make sure to not publish any db cred/general creds when using a `GET` request to the backend API endpoint. 

## Implementation sketch
* [x] Provision aws-rds instance 
* [x] Provision postgresql instance/db
* [x] create table/rows and import csv dataset via data.gov
* [x] Create API App
* [x] Bind app to postgresql db
* [x] `fetch` data from db via application api endpoint into an example pages site
* [x] Write up a KB Article on the process 

```[tasklist]
### Tasks
```

**Comment by apburnes** [comment]
Reach out to some engineers to pair on the next steps?

**Comment by Ephraim-G** [comment]
kb article: https://cloud.gov/pages/knowledge-base/website-api/
