### ISSUE TITLE
Spike deprecation of metrics-discovery-registrar and metrics-agent addons for CF v35.0+

### ISSUE THREAD

**Issue by cweibel** [cloud-gov/product#2810]
In order to upgrade to CF v35.0 and newer, figure out how the deprecation of metrics-discovery-registrar and metrics-agent addons.

## TODO

* [x] Test to see whether https://github.com/cloudfoundry/cf-deployment/releases/tag/v35.0.0 impacts us
* [x] Unpin version in CF pipeline, let flush through staging
* [x] Check grafana CF App, router stats still show
* [x] Check autoscaler still pulling CPU metrics for test app
* [x] If any of the above fail, create ops file to put back the values and come up with plan b

--- 

## Security considerations
None as of now

## Implementation sketch

* [x] Test out the todo's above in staging
* [x] Either come up with plan b (and new ticket) or roll to prod
