### ISSUE TITLE
Checklist for Onboarding Derrick

### ISSUE THREAD

**Issue by banesssa** [cloud-gov/product#2867]
# New ARP Contractor Onboarding Checklist

## Special Notes

- **Do not create this issue until the System Owner has formally authorized and requested it.**. You can get that OK by one of two ways:
  - A:
    - [ ] A: System Owner creates this issue
  - B:
    - [x] B.1: System owner emails cloud-gov-compliance@gsa.gov and cloud-gov-operations@gsa.gov with their authorization
    - [x] B.2: An operator adds a link to the Google Group conversation that includes the authorizing email.
      - https://groups.google.com/a/gsa.gov/g/cloud-gov-compliance/c/jD8H7qcOVUY
- **Please only use first names.**

---

In order to get `New Person` productively contributing to the cloud.gov team, `Buddy` should help `New Person` complete a prescribed set of tasks that will bring them up to speed and get them setup with cloud.gov.

## Role-Specific Onboarding

This onboarding ticket must be completed by all new cloud.gov team members. It must be paired with a role-specific onboarding ticket. Your onboarding buddy will create both.

## Instructions

Your onboarding buddy should reach out and introduce themselves to you. If you have not heard from them after a day or two, please let the team know.

1. Try to go through the checklists in order.
1. Make sure this issue is assigned you and your buddy in our [Github Project Planning Board](https://github.com/orgs/cloud-gov/projects/27/views/1). We use this board to organize, prioritize, and track our work.
1. If `Buddy` cannot complete any of the items on their checklist personally, _they are responsible for ensuring that someone with the correct access completes that item_.
1. Take notes on this onboarding process. If you notice a problem, let your buddy know by leaving a comment on this issue, or submit a fix yourself! You can propose a change to any documentation in GitHub using a pull request. The onboarding issue templates, including for this issue, are [here](https://github.com/cloud-gov/product/blob/main/.github/ISSUE_TEMPLATE).

## Pre-requisites

- [x] Complete [GSA OLU](https://gsaolu.gsa.gov/) IT Security & Privacy Awareness Training, which includes accepting the GSA IT Rules of Behavior. This is required before we can give you access to any cloud.gov systems. If you joined GSA more than two months ago, you've already completed this task and can check the box.
  - OLU has sometimes lost course completion data. We recommend downloading the PDF certificate of completion for each training and saving it to your Google Drive.

## Fulfill security and compliance requirements - Completed by onboarding buddy

- [x] Make sure they're in the [Team Roster](https://docs.google.com/spreadsheets/d/187663k5MYJBNlKExLu_nhuovcZQfIbqYCu2n4noNY1o/edit#gid=0).
- [x] Add their name, whether they're Cloud Operations, and the date they joined the team to the [training tracker](https://docs.google.com/spreadsheets/d/1hqU6cNeEB293OT0j3OvbdAFRkrf2zDOrPVxGfnr4sSw/edit#gid=0).
  - All engineers who are federal employees or staff contractors are part of Cloud Operations. Project contractors are not.
  - Copy the formulas for the due dates from an existing row (grab the "corner" of the cells and pull down).
  - As they complete training, fill out their completion dates in the [training tracker](https://docs.google.com/spreadsheets/d/1hqU6cNeEB293OT0j3OvbdAFRkrf2zDOrPVxGfnr4sSw/edit#gid=0).
- [x] Add them to the @cloud-gov-team [in Slack’s Team Directory](https://get.slack.help/hc/en-us/articles/212906697-User-Groups#edit-a-user-group).
- [x] Add them on GitHub to the [`cloud-gov-team`](https://github.com/orgs/cloud-gov/teams/cloud-gov-team) team, which will automatically invite them to our [`cloud-gov`](https://github.com/orgs/cloud-gov/people) organization.

## Complete cloud.gov trainings

Onboarding buddy: Contact the compliance team in [#cg-compliance](https://gsa.enterprise.slack.com/archives/C0A1Z7L2U) to schedule training(s).

- [x] Coordinate with your onboarding buddy to schedule [nonpublic information training](https://docs.google.com/presentation/d/1uB4MlGCu8ZYUxjKVZKwicQ95MvLxaT4Mh93y6w79GPw/edit#slide=id.p) within 60 days of joining the team (and annually after that). This will cover the following documents, which you should also review before or after training:
  - [x] Read our [sharing secret keys](https://cloud.gov/docs/ops/secrets/#sharing-secret-keys) policy.
  - [x] Review the [TTS requirements for password management](https://handbook.tts.gsa.gov/general-information-and-resources/tech-policies/password-requirements/).

## Getting to know cloud.gov

These items will help you come up to speed on cloud.gov and what it is, how it works, why it exists, etc. While you should take the time to go through them, please do not try and tackle it all in one shot! It can become overwhelming very quickly, so your onboarding buddy will walk through this list with you at a high level with you to help manage the work.

- [x] Read through [the Overview section of our site](https://cloud.gov/docs/overview/what-is-cloudgov/) for a broader understanding of cloud.gov, especially how we present it to potential customers and users.
- [x] Read [the team onboarding document](https://github.com/cloud-gov/product/blob/main/Onboarding.md) for more context about cloud.gov.
- [x] Bookmark the [pertinent links listed here](https://github.com/cloud-gov/product/blob/main/PertinentLinks.md).

## Team resources

You will automatically be added to one or more Google Drives: the [Cloud.gov All Staff Drive](https://drive.google.com/drive/folders/0ANH-Bql6mXGBUk9PVA) and, for federal employees, the [Cloud.gov Federal Employees Drive](https://drive.google.com/drive/folders/0AE_c0OLGmVIgUk9PVA). Put all documents related to cloud.gov in the appropriate shared drive so the team can access them and meet federal records requirements. Each drive contains a folder for each squad, and each squad folder contains a "wiki" that explains how the sub-folders are structured.

<details>
  <summary>
    Federal employees and staff contractors, expand this section:
  </summary>

- [ ] Subscribe to [the cloud.gov team calendar](https://calendar.google.com/calendar/embed?src=gsa.gov_0samf7guodi7o2jhdp0ec99aks@group.calendar.google.com&ctz=America/Los_Angeles) (click the + in the bottom right) so you know when assorted team meetings are happening in the various squads. Tip: When you plan Out of Office time, make a calendar event for that on the cloud.gov calendar so that your teammates know you'll be away.

</details>

## Slack Channels

The following cloud.gov channels are public and all team members are welcome to join:

- [x] `#cg-aws-status` - bots post announcements about AWS service outages/incidents
- [x] `#cg-business` - business development (if applicable)
- [x] `#cg-compliance` - compliance-related information and discussion
- [x] `#cg-customer-success` - customer success squad channel
- [x] `#cg-general` - program-level information and discussion
- [x] `#cg-offtopic` - off-topic team sharing
- [x] `#cg-platform-news` (🗣️) - bots post platform alerts (mostly CI job notifications)
- [x] `#cg-platform` - platform operations
- [x] `#cg-support` (🗣️) - support requests and assistance within TTS
- [x] `#cg-supportstream` (🗣️) - stream of activity on Zendesk tickets
- [x] `#cloud-gov` (🗣️) - bots post announcements here

Channels marked with (🗣️) receive a lot of messages, either from customers or bots, and you may want to mute them.

- [x] Project contractors: Your buddy will add you to the private channel for your project.

<details>
  <summary>
    For federal employees only:
  </summary>

- [ ] `#cg-priv-gov` - may contain discussion of contracting-related or other private, federal-employee-only comms

</details>

## Google Groups and Spaces

We manage calendar invites and Google Drive access using Google Groups. Some groups can also receive message from outside emails.

- [x] Project contractors: Add them to the [cloud.gov Project Contractors Google Group](https://groups.google.com/a/gsa.gov/g/cloud-gov-project-contractors/members) as the "Member" role. This grants them Commenter access to the All Staff Google Drive. If they are working on a project in a specific folder, you can grant them greater access to that folder.

<details>
  <summary>
    Federal employees and staff contractors, expand this section:
  </summary>

Add them to the following Google Groups:

- [ ] [cloud.gov Team](https://groups.google.com/a/gsa.gov/g/cloud-gov/members) so they can participate in team-wide internal communication.
- [ ] Business Unit Only - Add them to the [cloud.gov inquiries Google Group](https://groups.google.com/a/gsa.gov/g/cloud-gov-inquiries/members) so they can keep apprised of prospective new clients.

You will automatically be added to the Google Space [CG-PRIV](https://mail.google.com/mail/u/0/#chat/space/AAAAr60JXAc), a fallback team communication channel in the event Slack is down.

They may need added to one or more of these team-specific groups:

- [ ] [cloud.gov Assurance Team](https://groups.google.com/a/gsa.gov/g/cloud-gov-assurance/members)
- [ ] [cloud.gov Compliance](https://groups.google.com/a/gsa.gov/g/cloud-gov-compliance/members) (external email accepted)
- [ ] [cloud.gov Customer Success Team](https://groups.google.com/a/gsa.gov/g/cloud-gov-customer-success/members)

Lastly, for federal employees only:

- [ ] [cloud.gov Federal Employees](https://groups.google.com/a/gsa.gov/g/cloud-gov-federal-employees/members)
- [ ] Make them a Space Manager in [CG-PRIV](https://mail.google.com/mail/u/0/#chat/space/AAAAr60JXAc).

</details>

**Comment by cweibel** [comment]
Switched to newer template James provided.  Thank you!
