### ISSUE TITLE
Create customer facing templates for RDS upgrades

### ISSUE THREAD

**Issue by cweibel** [cloud-gov/product#2872]
In order to notify our customers that they have retiring instance types and database engine versions, we need to identify the databases impacted and provide upgrade guidance

 - Customer dbs on t2 and m4 we need to move for reserved instance costs, being retired by April by AWS
 - Customer dbs on postgres 11.x will cost us starting april 1 (https://docs.aws.amazon.com/AmazonRDS/latest/PostgreSQLReleaseNotes/postgresql-release-calendar.html)
 - Customers dbs on mysql 5.7.x will cost us starting april 1 (https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/MySQL.Concepts.VersionMgmt.html)

## Tasks
* [x] Create email template for engine version upgrades
* [x] Create email template for instance type upgrades
* [x] Get language approved by the Business team
* [x] Create script to identify customers/platform impacted rds instances
* [x] Review with the Success team

--- 

## Security considerations
There should be no changes to security boundaries, practices, documentation, risk that arise directly from this story

## Implementation sketch

Pseudo code:

```
    if (family = t2,m4) and (pg 11.19 or mysql 5.7.32)
        customer needs to upgrade instance type and perform engine upgrade
    elseif  !(family = t2,m4) and (pg 11.19 or mysql 5.7.32)
        customer needs to upgrade engine
    elseif  (family = t2,m4) and !(pg 11.19 or mysql 5.7.32)
        customer needs to upgrade instance type
    else
        db is fine, leave alone
    end if
```
