### ISSUE TITLE
Logging/Observability system improvements

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/product#2915]
# What we're after

https://github.com/cloud-gov/private/issues/740 covered creating a new logging/observability platform on OpenSearch to replace the old ELK system. The initial epic was focused only on delivering a system with feature parity with ELK to get a solution out to customers as fast possible.

This epic will cover the work to enhance the functionality of the system.

---

### Related issues/sub-tasks

```[tasklist]
### Tasks
- [ ] https://github.com/cloud-gov/private/issues/729
- [ ] https://github.com/cloud-gov/private/issues/730
- [ ] https://github.com/cloud-gov/private/issues/731
- [ ] https://github.com/cloud-gov/private/issues/686
- [ ] https://github.com/cloud-gov/kibana-cf-auth-proxy/issues/52
- [ ] https://github.com/cloud-gov/private/issues/737
- [ ] https://github.com/cloud-gov/aws-broker/issues/254
- [ ] https://github.com/cloud-gov/private/issues/744
- [ ] https://github.com/cloud-gov/private/issues/745
- [ ] https://github.com/cloud-gov/private/issues/743
- [ ] https://github.com/cloud-gov/private/issues/742
- [ ] https://github.com/cloud-gov/private/issues/741
- [ ] https://github.com/cloud-gov/private/issues/746
- [ ] https://github.com/cloud-gov/private/issues/747
- [ ] https://github.com/cloud-gov/private/issues/748
- [ ] https://github.com/cloud-gov/private/issues/750
- [ ] https://github.com/cloud-gov/private/issues/749
- [ ] https://github.com/cloud-gov/private/issues/751
- [ ] https://github.com/cloud-gov/private/issues/752
- [ ] https://github.com/cloud-gov/private/issues/753
- [ ] https://github.com/cloud-gov/private/issues/754
- [ ] https://github.com/cloud-gov/private/issues/755
- [ ] https://github.com/cloud-gov/private/issues/756
- [ ] https://github.com/cloud-gov/private/issues/757
- [ ] https://github.com/cloud-gov/private/issues/789
- [ ] https://github.com/cloud-gov/opensearch-boshrelease/issues/1
- [ ] https://github.com/cloud-gov/opensearch-boshrelease/issues/3
- [ ] https://github.com/cloud-gov/private/issues/798
- [ ] https://github.com/cloud-gov/private/issues/799
- [ ] https://github.com/cloud-gov/private/issues/800
- [ ] https://github.com/cloud-gov/private/issues/801
- [ ] https://github.com/cloud-gov/private/issues/802
- [ ] https://github.com/cloud-gov/private/issues/803
- [ ] https://github.com/cloud-gov/private/issues/805
- [ ] https://github.com/cloud-gov/private/issues/804
- [ ] https://github.com/cloud-gov/private/issues/807
- [ ] https://github.com/cloud-gov/private/issues/809
- [ ] https://github.com/cloud-gov/opensearch-boshrelease/issues/11
- [ ] https://github.com/cloud-gov/opensearch-boshrelease/issues/12
- [ ] https://github.com/cloud-gov/kibana-cf-auth-proxy/issues/66
- [ ] https://github.com/cloud-gov/private/issues/835
- [ ] https://github.com/cloud-gov/private/issues/836
- [ ] https://github.com/cloud-gov/private/issues/864
- [ ] https://github.com/cloud-gov/private/issues/865
- [ ] https://github.com/cloud-gov/private/issues/906
- [ ] https://github.com/cloud-gov/private/issues/919
- [ ] https://github.com/cloud-gov/private/issues/920
- [ ] https://github.com/cloud-gov/private/issues/921
- [ ] https://github.com/cloud-gov/private/issues/936
- [ ] https://github.com/cloud-gov/private/issues/953
- [ ] https://github.com/cloud-gov/opensearch-dashboards-cf-auth-proxy/issues/97
```
